image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
   - npm install
   - CI=true npm run build
   - rm -rf public
   - mv build public
  artifacts:
    paths:
      - public
  only:
   - master